### ISSUE TITLE
Laguage

### ISSUE THREAD

**Issue by simlive** [Snoopy1753199432/Mine#1]
I have a question, author, have you finished the Chineseization of this File Converter v1.2.3 software, I saw that the original author wrote your name on it, thank you for your Chineseization work. If so, you can use the Chinese version of this software, the author please reply in your busy schedule after seeing it.
我有一个问题，作者，你是不是已经对这个File Converter v1.2.3软件进行了汉化，我看到原作者把你的名字写上去去了，感谢你的汉化工作。如果是的话，就可以使用这个软件的汉化版本了，作者看到后请于百忙之中回复一下。

**Comment by Snoopy1866** [comment]
Yes, I have finished the Chineses Localization of File Conveter v1.2.3 software, thanks you for your developing on this excellent software! By the way, although I have try to translate some English words to Chineses word, some words have not been translated properly because of my lacking of professional knowledge in video decode and encode. Please update this localization if you find any mistake.


是的，我已经完成了Chineses的本地化，文件Conveter v1.2.3软件，感谢您开发了此优秀软件！顺便说一句，尽管我试图将一些英语单词翻译成Chineses单词，但由于我缺乏视频编解码的专业知识，因此某些单词尚未正确翻译。如果发现任何错误，请更新此本地化。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月2日(星期五) 中午11:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [Snoopy1866/Mine] Laguage (Issue #1)





 
I have a question, author, have you finished the Chineseization of this File Converter v1.2.3 software, I saw that the original author wrote your name on it, thank you for your Chineseization work. If so, you can use the Chinese version of this software, the author please reply in your busy schedule after seeing it.
 我有一个问题，作者，你是不是已经对这个File Converter v1.2.3软件进行了汉化，我看到原作者把你的名字写上去去了，感谢你的汉化工作。如果是的话，就可以使用这个软件的汉化版本了，作者看到后请于百忙之中回复一下。

**Comment by simlive** [comment]
Thank you for your software Chineseization work. I am not a software author, but a reader. I just saw that the original author of the software, Tichau, updated the language 13 days ago, and thank you for your Chineseization. "Thanks to Snoopy1866 for the Simplified Chinese localization."
You should have seen it too. Since I can't contact the original author Tichau, I can't use the Chinese version.If you have updated the Chinese version. Can you teach me how to do it.
感谢你的软件汉化工作，我本人不是软件作者，是一名读者，最近刚好看到，软件原作者Tichau，13天前更新了语言，并向你的汉化致谢。”Thanks to Snoopy1866 for the Simplified Chinese localization. “
你应该也看到了，由于联系不到原作者Tichau，我还没办法使用汉化版本，你如果已经更新了汉化，可以教我如何进行汉化吗。

**Comment by Snoopy1866** [comment]
You can go to this website: [Localization](https://github.com/Tichau/FileConverter/wiki/Localization), follow the localization steps to update the zh-CN.resx

可以在这个网址中找到汉化方法：[Localization](https://github.com/Tichau/FileConverter/wiki/Localization)，这个软件是跟系统语言走的，所以暂时没法先自行汉化使用，只能等原作者合并了。
